### ISSUE TITLE
Simple configuration on Linux

### ISSUE THREAD

**Issue by gregoiregentil** [eycorsican/leaf#375]
I'm on Linux. What is the simplest configuration to redirect all the traffic to a 127.0.0.1 proxy on port 4000?

```
[General]
dns-server = 223.5.5.5
tun = auto

[Proxy]
Direct = direct
socks-interface = 127.0.0.1
socks-port = 4000
```

Do I need to openvpn --mktun and ifconfig or is it done by tun=auto?

**Comment by eycorsican** [comment]
The most simple config to run leaf on Linux with TUN (requires root permission) is:

```ini
[General]
tun=auto
[Proxy]
out1=direct
```

You can check the routing table to see if `tun=auto` works properly for you:

```shell
ip route show table main
ip route show table default
```

I wouldn't recommend a local outbound when using the TUN inbound because the traffic sending out  from your local socks5 proxy would catch by the TUN again.

Remote socks5  server would work:

```ini
[General]
tun=auto
[Proxy]
out1=socks,1.2.3.4,4000
```

**Comment by gregoiregentil** [comment]
Thank you very much for helping. leaf is a great project but the documentation is thin! (a little bit too much parsed...) More tutorials would be helpful.

Yes, it's working after running leaf as root (which makes some sense to me in order to create the tun interface).
