### ISSUE TITLE
Android: how to deal with VpnService protect now?

### ISSUE THREAD

**Issue by gregoiregentil** [eycorsican/leaf#376]
I'm trying to integrate leaf in Android and I have adapted some code from aleaf. This project has the protect.sock file in Java/Kotlin with its corresponding pathfile passed to leaf.

This has disappeared since March 2023 and there is now a JNI callback architecture to communicate between leaf and JNI regarding VpnService protect. There are some comments in the code but no example so it's a little bit confusing / difficult.

My config has:
[Proxy]
Socks = socks, 127.0.0.1, port
with my own code to deal with socks inside my app. I'm also dealing with protect regarding my own code. I just need to redirect the whole traffic to socks so I'm calling leaf_run from my VpnService class.

Do I still need a glue layer between leaf and Android regarding protect?

If I was using Direct in the configuration, would Leaf need this glue to reach VpnService protect?

Isn't it possible to come back to the legacy protect architecture with a .sock file which seems "easier"?

Bonus question (!): I have loglevel=debug in my config, but I'm not getting anything in logcat. How could I debug what's going on in leaf on Android?

**Comment by eycorsican** [comment]
Protecting sockets on Android through Unix socket or TCP connection is still [supported](https://github.com/eycorsican/leaf/blob/4b4338b59fe9a35589986ed04215e4d338e49526/leaf/src/proxy/mod.rs#L124), the interface is simple, on every connection leaf writes the fd as i32 for the other end to protect, and reads an i32 as the result. Regarding the JNI interface, it's "the easier" way in my opinion, you define a protect function with the required signature in you Android VpnService class, [tell leaf the name of that function](https://github.com/eycorsican/leaf/blob/4b4338b59fe9a35589986ed04215e4d338e49526/leaf/src/mobile/callback.rs#L65), leaf will call the function everytime it needs to protect an outbound socket.

**Rather than protecting the sockets, perhaps you can just add your VPN package to the [disallowed list](https://developer.android.com/reference/android/net/VpnService.Builder#addDisallowedApplication(java.lang.String)).**

Logging works on Android, you should find the logs in logcat, maybe double check your setups?

**Comment by gregoiregentil** [comment]
Thank you again for helping. I have fixed my rust binding problem, I now see the leaf logs in logcat, I'm using disallowed package and I have dumped all my protect code which is not necessary any more (if only I had knew that API before!!!)

I got your your point about the protect binding. As it's new, I would suggest that you paste here the new ten lines of java/kotlin with protect function and its correct signature as it might be useful to someone one else.

Thank you.
